import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const BRIEFS_DIR = join(homedir(), 'MacTaverne', 'bud', 'briefs');

function ensureBriefsDir() {
  if (!existsSync(BRIEFS_DIR)) {
    mkdirSync(BRIEFS_DIR, { recursive: true });
  }
}

function formatBrief(data, evaluation) {
  const { date, arrivals, departures, occupancy, upcoming, scrapedAt } = data;
  const { flags } = evaluation;

  const dateLabel = new Date(date).toLocaleDateString('en-CA', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });

  const lines = [
    `# MacTaverne — Morning Brief`,
    `**${dateLabel}**`,
    `*Fetched: ${new Date(scrapedAt).toLocaleTimeString('en-CA', { hour: '2-digit', minute: '2-digit' })}*`,
    '',
  ];

  // Flags / alerts
  if (flags.length > 0) {
    lines.push('## Flags');
    for (const flag of flags) {
      const icon = flag.type === 'alert' ? '🔴' : flag.type === 'warning' ? '🟡' : '🔵';
      lines.push(`- ${icon} ${flag.message}`);
    }
    lines.push('');
  }

  // Occupancy stats
  if (occupancy.length > 0) {
    lines.push('## Occupancy');
    for (const stat of occupancy) {
      lines.push(`- **${stat.label}**: ${stat.value}`);
    }
    lines.push('');
  }

  // Arrivals
  lines.push(`## Arrivals (${arrivals.length})`);
  if (arrivals.length === 0) {
    lines.push('None today.');
  } else {
    for (const a of arrivals) {
      const parts = [`- **${a.guest}**`];
      if (a.room) parts.push(`Room ${a.room}`);
      if (a.checkIn) parts.push(`ETA ${a.checkIn}`);
      if (a.status) parts.push(`[${a.status}]`);
      lines.push(parts.join(' · '));
      if (a.notes) lines.push(`  > ${a.notes}`);
    }
  }
  lines.push('');

  // Departures
  lines.push(`## Departures (${departures.length})`);
  if (departures.length === 0) {
    lines.push('None today.');
  } else {
    for (const d of departures) {
      const parts = [`- **${d.guest}**`];
      if (d.room) parts.push(`Room ${d.room}`);
      if (d.checkOut) parts.push(`by ${d.checkOut}`);
      if (d.status) parts.push(`[${d.status}]`);
      lines.push(parts.join(' · '));
    }
  }
  lines.push('');

  // Upcoming
  if (upcoming.length > 0) {
    lines.push(`## Upcoming Bookings (next 7 days)`);
    for (const b of upcoming) {
      const parts = [`- **${b.guest}**`];
      if (b.checkIn) parts.push(`in ${b.checkIn}`);
      if (b.checkOut) parts.push(`→ out ${b.checkOut}`);
      if (b.room) parts.push(`Room ${b.room}`);
      if (b.amount) parts.push(`${b.amount}`);
      if (b.status) parts.push(`[${b.status}]`);
      lines.push(parts.join(' · '));
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Bud hotelier-mcp*`);

  return lines.join('\n');
}

export function writeDailyBrief(data, evaluation) {
  ensureBriefsDir();

  const filename = `${data.date}.md`;
  const filepath = join(BRIEFS_DIR, filename);
  const content = formatBrief(data, evaluation);

  writeFileSync(filepath, content, 'utf8');
  return { filepath, content };
}

export function getBriefsDir() {
  return BRIEFS_DIR;
}
